baseurl = "https://gchape.github.io/"

title = "Blog"
theme = "whiteplain"
languageCode = "en"

disqusShortname = "Shortname"
googleAnalytics = "Tracking ID"

copyright = "&copy; Copyright 2024"

[params]
# This is displayer in About page.
[params.author]
  name = "Giorgi Chapidze"
  gravatar = "Gravatar email or MD5 Hash"

#  x = "X username"
#  twitter = "Twitter username"
#  facebook = "Facebook username"
#  googleplus = "Googleplus username"
#  instagram = "Instagram username"
#  threads = "Threads username"
#  tumblr = "Tumblr username"
#  flickr = "Flickr username"
#  reddit = "Reddit username"
  linkedin = "Linkedin username"
#  slideshare = "Slideshare username"
  github = "gchape"
#  gitlab = "Gitlab username"
#  bitbucket = "Bitbucket username"
#  stackoverflow = "Stackoverflow username"
#  jsfiddle = "Jsfiddle username"
#  codepen = "Codepen username"
#  deviantart = "Deviantart username"
#  behance = "Behance username"
#  dribbble = "Dribbble username"
#  wordpress = "Wordpress username"
#  medium = "Medium username"
#  foursquare = "Foursquare username"
#  xing = "Xing username"
#  quora = "Quora username"
#  youtube = "YouTube username"
#  tiktok = "TikTok username"
#  vimeo = "Vimeo username"
#  whatsapp = "Whatsapp username"
#  skype = "Skype username"
#  snapchat = "Snapchat username"
#  pinterest = "Pinterest username"
#  telegram = "Telegram username"
#  vine = "Vine username"
  email = "Your email"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
